### ISSUE TITLE
v1

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/repo-info#1]
Specs: https://github.com/firstandthird/repos/wiki/v1-Specs

**Comment by jgallen23** [comment]
@Belelros want to read this over?  Going to want your help with it

**Comment by Antonio-Laguna** [comment]
Yes I will today!

## 

Sent from my mobile device

**Comment by jgallen23** [comment]
getting this error

```
TypeError: Cannot call method 'forEach' of undefined
    at /Users/jga/code/repos/modules/ghrepo.js:101:21
    at Request._callback (/Users/jga/code/repos/modules/request.js:48:7)
    at Request.self.callback (/Users/jga/code/repos/node_modules/request/request.js:121:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/Users/jga/code/repos/node_modules/request/request.js:978:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/jga/code/repos/node_modules/request/request.js:929:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

**Comment by Antonio-Laguna** [comment]
Can you give me what you're using to call it? By mail!

On Tuesday, March 4, 2014, Greg Allen notifications@github.com wrote:

> getting this error
> 
> TypeError: Cannot call method 'forEach' of undefined
>     at /Users/jga/code/repos/modules/ghrepo.js:101:21
>     at Request._callback (/Users/jga/code/repos/modules/request.js:48:7)
>     at Request.self.callback (/Users/jga/code/repos/node_modules/request/request.js:121:22)
>     at Request.EventEmitter.emit (events.js:98:17)
>     at Request.<anonymous> (/Users/jga/code/repos/node_modules/request/request.js:978:14)
>     at Request.EventEmitter.emit (events.js:117:20)
>     at IncomingMessage.<anonymous> (/Users/jga/code/repos/node_modules/request/request.js:929:12)
>     at IncomingMessage.EventEmitter.emit (events.js:117:20)
>     at _stream_readable.js:920:16
>     at process._tickCallback (node.js:415:13)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/firstandthird/repos/issues/1#issuecomment-36645373
> .

## 

Sent from my mobile device

**Comment by Antonio-Laguna** [comment]
Last commit will solve that issue. The response from an empty repo doesn't come in the docs
